BEOperations/urls.py
from django.contrib import admin

from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from beweb import forms, views
from datetime import datetime
from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', views.home, name='home'),
    path('api-token-auth/', obtain_auth_token,
         name='api_token_auth'),  # <-- And here
    path('beapi/', include('beapi.urls', namespace='beapi')),
    path('beweb/', include('beweb.urls', namespace='beweb')),
    # path('e117/', include('e117.urls', namespace='e117')),
    path('login/',
         LoginView.as_view
         (
             template_name='beweb/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context={
                 'note': 'Log in',
                 'title': 'Log in',
                 'year': datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),
    path('admin/', admin.site.urls, name="admin"),
    path('api-auth', include('rest_framework.urls')),
    url('^', include('django.contrib.auth.urls')),
    # url(r'^report_builder/', include('report_builder.urls'))
    # url(r'^api-token-auth/', obtain_auth_token)
]

beapi/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from rest_framework.authtoken import views
from rest_framework_swagger.views import get_swagger_view


app_name = 'beapi'

schema_view = get_swagger_view(
    title="BE Operations API Endpoints Documentation")


urlpatterns = [
    # Appflow
    path('appflow', Appflows.as_view(), name="appflow"),
    path('appflowpost', AppflowsPost.as_view(), name="appflowpost"),
    path('appflowdelete/<pk>', AppflowDelete.as_view(), name='appflowdelete'),
    path('appflowmodify/<pk>', AppflowModify.as_view(), name='appflowmodify'),
    path('appflowupdate/<pk>', AppflowUpdate.as_view(), name='appflowmodify'),

    # Workorders
    path('workorder', Workorders.as_view(), name="workorder"),
    path('workorders/<pk>/',WorkorderJobs.as_view(), name="workorders"),
    path('workorderpost', WorkordersPost.as_view(), name="workorderpost"),
    path('workorderdelete/<pk>', WorkorderDelete.as_view(), name="workorderdelete"),
    path('workorderput/<pk>', WorkorderModify.as_view(), name="workorderput"),
    path('workorderpatch/<pk>', WorkOrderUpdate.as_view(), name="workorderpatch"),
    path('docs/', schema_view, name="schema_view"),

    # Jobs
    path('jobs', Jobs.as_view(), name="jobs"),
    path('jobs/artisan/<assignee>/', AssignedJobs.as_view(), name="artisan-jobs"),
    path('job/<pk>/', JobGet.as_view(), name="job"),
    path('jobpost', JobCreate.as_view(), name="jobpost"),
    path('jobdelete/<pk>', JobDelete.as_view(), name="jobdelete"),
    path('jobupdate/<pk>', JobUpdate.as_view(), name="jobupdate"),


    # Clients
    path('clients', Clients.as_view(), name="clients"),
    path('client/<pk>/', ClientGet.as_view(), name="client"),
    path('clientpost/', ClientCreate.as_view(), name="clientpost"),
    path('clientdelete/<pk>/', ClientDelete.as_view(), name="clientdelete"),
    path('clientupdate/<pk>/', ClientUpdate.as_view(), name="clientupdate"),

    # Feeders
    path('feeders', Feeders.as_view(), name="feeders"),
    path('feeder/<pk>', FeederGet.as_view(), name="feeder"),
    path('feederpost', FeederCreate.as_view(), name="feederpost"),
    path('feederdelete/<pk>', FeederDelete.as_view(), name="feederdelete"),
    path('feederupdate/<pk>', FeederUpdate.as_view(), name="feederupdate"),
    # LightningArresters
    path('lightningarresters', LightningArresters.as_view(),name="lightningarresters"),
    path('lightningarrester/<pk>', LightningArresterGet.as_view(),name="lightningarrester"),
    path('lightningarresterpost', LightningArresterCreate.as_view(),name="lightningarresterpost"),
    path('lightningarresterdelete/<pk>',LightningArresterDelete.as_view(), name="lightningarresterdelete"),
    path('lightningarresterupdate/<pk>',LightningArresterUpdate.as_view(), name="lightningarresterupdate"),


    # SubstationMeter
    path('substationmeters', SubstationMeters.as_view(), name="substationmeters"),
    path('substationmeter/<pk>', SubstationMeterGet.as_view(),name="substationmeter"),
    path('substationmeterpost', SubstationMeterCreate.as_view(),name="substationmeterpost"),
    path('substationmeterdelete/<pk>', SubstationMeterDelete.as_view(),name="substationmeterdelete"),
    path('substationmeterupdate/<pk>', SubstationMeterUpdate.as_view(),name="substationmeterupdate"),
    # Switchgear
    path('switchgears', Switchgears.as_view(), name="switchgears"),
    path('switchgear/<pk>', SwitchgearGet.as_view(), name="switchgear"),
    path('switchgearpost', SwitchgearCreate.as_view(), name="switchgearpost"),
    path('switchgeardelete/<pk>', SwitchgearDelete.as_view(),name="switchgeardelete"),
    path('switchgearupdate/<pk>', SwitchgearUpdate.as_view(),name="switchgearupdate"),
    # Transformer
    path('transformers', Transformers.as_view(), name="transformers"),
    path('transformer/<pk>', TransformerGet.as_view(), name="transformer"),
    path('transformerpost', TransformerCreate.as_view(), name="transformerpost"),
    path('transformerdelete/<pk>', TransformerDelete.as_view(),name="transformerdelete"),
    path('transformerupdate/<pk>', TransformerUpdate.as_view(),name="transformerupdate"),
    # BOQ Labour
    path('boqslabour', BoqsLabour.as_view(), name="boqslabour"),
    path('boqlabour/<pk>', BoqLabourGet.as_view(), name="boqlabour"),
    path('boqlabourpost', BoqLabourCreate.as_view(), name="boqlabourpost"),
    path('boqlabourdelete/<pk>', BoqLabourDelete.as_view(), name="boqlabourdelete"),
    path('boqlabourupdate/<pk>', BoqLabourUpdate.as_view(), name="boqlabourupdate"),
    # BOQ Material
    path('boqmaterials', BoqMaterial.as_view(), name="boqmaterials"),
    path('boqmaterial/<pk>', BoqMaterialGet.as_view(), name="boqmaterial"),
    path('boqmaterialpost', BoqMaterialCreate.as_view(), name="boqmaterialpost"),
    path('boqmaterialdelete/<pk>', BoqMaterialDelete.as_view(),name="boqmaterialdelete"),
    path('boqmaterialupdate/<pk>', BoqMaterialUpdate.as_view(),name="boqmaterialupdate"),
    # BOQ Vehicles
    path('boqvehicles', BoqVehicle.as_view(), name="boqvehicles"),
    path('boqvehicle/<pk>', BoqVehicleGet.as_view(), name="boqvehicle"),
    path('boqvehiclepost', BoqVehicleCreate.as_view(), name="boqvehiclepost"),
    path('boqvehicledelete/<pk>', BoqVehicleDelete.as_view(),name="boqvehicledelete"),
    path('boqvehicleupdate/<pk>', BoqVehicleUpdate.as_view(),name="boqvehicleupdate"),
    path('workorderpatch/<pk>', WorkOrderUpdate.as_view(), name="workorderpatch"),

    # Workflow urls
    path('workflow', Workflows.as_view(), name="workflow"),
    path('workflowpost', WorkflowsPost.as_view(), name="workflowpost"),
    path('workflowdelete/<pk>', WorkflowDelete.as_view(), name="workflowdelete"),
    path('workflowpatch/<pk>', WorkflowUpdate.as_view(), name="workflowpatch"),

    # User role trail urls
    path('userroletrail', UserRoleTrails.as_view(), name="userroletrail"),
    path('userroletrailpost', UserRoleTrailsPost.as_view(),name="userroletrailpost"),
    path('userroletraildelete/<pk>', UserRoleTrailDelete.as_view(),name="userroletraildelete"),
    path('userroletrailpatch/<pk>', UserRoleTrailUpdate.as_view(),name="userroletrailpatch"),

    # workorder urls
    path('workorder', Workorders.as_view(), name="workorder"),
    path('workorderpost', WorkordersPost.as_view(), name="workorderpost"),
    path('workorderdelete/<pk>', WorkorderDelete.as_view(), name="workorderdelete"),

    # Jobteam urls
    path('jobteams', JobteamGet.as_view(), name="jobteams"),
    path('jobteam/<pk>', JobTeam.as_view(), name="jobteam"),
    path('jobteams/<job_progress>', SpecificJobTeam.as_view(), name="jobteams"),
    path('jobteampost', JobteamPost.as_view(), name="jobteampost"),
    path('jobteamdelete/<pk>', JobteamDelete.as_view(), name="jobteamdelete"),
    path('jobteamupdate/<pk>', JobteamUpdate.as_view(), name="jobteamupdate"),

    # Jobsync urls
    path('jobsync', JobsyncGet.as_view(), name="jobsync"),
    path('jobsync/<pk>', Jobsync.as_view(), name="jobsyncid"),
    path('jobsyncpost', JobsyncPost.as_view(), name="jobsyncpost"),
    path('jobsyncdelete/<pk>', JobsyncDelete.as_view(), name="jobsyncdelete"),
    path('jobsyncupdate/<pk>', JobsyncUpdate.as_view(), name="jobsyncupdate"),

    # jobprogress urls
    path('artisan/jobprogress/<job_id>/',SingleJobProgress.as_view(), name="artisan-jobprogress"),
    path('jobprogress', JobprogressGet.as_view(), name="jobprogress"),
    path('jobprogress/<pk>', JobProgress.as_view(), name="jobprogressid"),
    path('jobprogresspost', JobprogressPost.as_view(), name="jobprogresspost"),
    path('jobprogressdelete/<pk>', JobprogressDelete.as_view(),name="jobprogressdelete"),
    path('jobprogressupdate/<pk>', JobprogressUpdate.as_view(),name="jobprogressupdate"),


    # E84Line Inspection urls
    path('e84line', E84LineinspectionGet.as_view(), name="e84line"),
    path('e84line/<pk>', E84LineInspection.as_view(), name="e84lineid"),
    path('e84linepost', E84LineinspectionPost.as_view(), name="e84linepost"),
    path('e84linedelete', E84LineinspectionDelete.as_view(), name="e84linedelete"),
    path('e84lineupdate/<pk>/', E84LineinspectionUpdate.as_view(),name="e84lineupdate"),

    # E84General urls
    path('e84general', E84GeneralGet.as_view(), name="e84general"),
    path('e84general/<pk>', E84general.as_view(), name="e84generalid"),
    path('e84generalpost', E84GeneralPost.as_view(), name="e84generalpost"),
    path('e84generaldelete/<pk>', E84GeneralDelete.as_view(),name="e84generaldelete"),
    path('e84generalupdate/<pk>/', E84GeneralUpdate.as_view(),name="e84generalupdate"),

    # E60 urls
    path('e60s', E60sGet.as_view(), name="e60s"),
    path('e60job/<job>/',E60sByJobId.as_view(),name="e60job"),
    path('e60/<pk>', E60s.as_view(), name="e60/"),
    path('e60post', E60Post.as_view(),name="e60post/"),
    path('e60delete/<pk>', E60Delete.as_view(),name="e60delete/"),
    path('e60update/<pk>', E60Update.as_view(),name="e60update/"),


    # E60Transformer urls
    path('e60/transformer/<e60_id>/',E60TransformersByE60Id.as_view(),name="e60-transformer"),
    path('e60transformers', E60TransformerGet.as_view(), name="e60transformers"),
    path('e60transformer/<pk>', E60Transformers.as_view(), name="e60transformerid"),
    path('e60transformerpost', E60TransformerPost.as_view(),name="e60transformerpost"),
    path('e60transformerdelete/<pk>', E60TransformerDelete.as_view(),name="e60transformerdelete"),
    path('e60transformerupdate/<pk>', E60TransformerUpdate.as_view(),name="e60transformerupdate"),

    # E60Switchgear urls
    path('e60/switchgear/<e60_id>/',E60SwitchgearByE60Id.as_view(),name="e60-switchgear"),
    path('e60switchgears', E60SwitchgearGet.as_view(), name="e60switchgears"),
    path('e60switchgear/<pk>', E60Switchgears.as_view(), name="e60switchgearid"),

beweb/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . forms import *
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from graphene_django.views import GraphQLView
from .views import *
app_name = 'beweb'

urlpatterns = [
    path('graphql', GraphQLView.as_view( graphiql=True)),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('landing', views.landing, name='landing'),
    path('jobs',views.viewJobs,name='jobs'),
    path('listjobs/',ListJobs.as_view(),name='listjobs'),
    path('sjob',views.seejob,name='sjob'),
    path('editjob/',views.editjob,name='editjob'),
    # path('reassignjob/',views.reassignjob,name='reassignjob'),
    path('changejob/',views.ChangeJob.as_view(),name='changejob'),
    path('job/reassign/',views.JobReassign.as_view(),name='job/reassign'),
    path('job/',views.job,name='job'),
    path('mywork/', workorder, name='mywork'),
    path('api/login', views.login),
    path('addjob/', AddJob.as_view(), name='addjob'),
    path('getteam/', MyTeam.as_view(), name='getteam'),
    path('getmyteam/', MTeam.as_view(), name='getmyteam'),
    path('getasset/', MyAsset.as_view(), name='getasset'),
    path('updatejobasset/', MyjobAsset.as_view(), name='updatejobasset'),
    path('getwoid/', Mywo.as_view(), name='getwoid'),
    path('save/asset/', SaveJobandAddAsset.as_view(), name='SaveJobandAddAsset'),
    path('save/job/', SaveJob.as_view(), name='SaveJob'),
    path('create/e117/', SaveE117Job.as_view(), name='e117-create'),  
    path('saveasset/', WoSaveAsset.as_view(), name='saveasset'),
    path('get_user/', views.get_user, name='get_user'),
    path('addteam/', views.addteam, name='addteam'),
    path('create/', views.create, name='create'),
    path('create_e117/',Create_E117_Job.as_view(),name='create_e117'),
    path('newteam/', views.create_team, name='newteam'),
    path('view_teams/',views.view_Teams,name='view_teams'),
    path('team/<ec_number>',views.view_Team,name='team'),
    path('editteam/',views.editTeam,name='editteam'),  
    path('orders/<ec_num>/', JobsViewSet.as_view(),name="orders"),
    path('openjobs/<username>/<section>/<status>/', JobsViewProcedure.as_view(),name="openjobs"),
    path('progressjobs/<username>/<section>/<status>/', ProgressJobs.as_view(), name="progressjobs"),
    path('jobsreport/<jobtype>/<centre>/<status>/<start_date>/<end_date>/',JobsReports.as_view(),name="jobsreport"),
    path('workorders_report/<workorder_centre>/<workorder_status>/<workorder_start_date>/<workorder_end_date>/',WorkordersReports.as_view(),name="workorders_report"),
    path('rejectedjobs/', ReinspectionJobs.as_view(), name="rejectedjobs"),
    path('supervisorjobs/<username>/<section>/<status>/', SuspendedJobs.as_view(),name="supervisorjobs"),
    path('workorders/<centre>/',WorkorderViewSet.as_view(),name='workorders'),
    path('save/workorder/', OnlySaveWorkorder.as_view(), name='saveworkorder'),
    path('editwork/', editwork, name='editwork'),
    path('edit/', SaveEditedWorkorder.as_view(), name='saveeditedworkorder'),
    path('form/<job_id>/', FormsView.as_view(), name='form'),
    path('Jobworkflow/', views.Job_workflow, name='Jobworkflow'),
    path('forms/', views.listForms, name='forms'),
    path('display/e84/',views.displayE84Form,name='e84-display'),
    path('E117/',views.e117Form,name='e117-display'),
    path('E84/',e84Form,name='e84-view'),
    path('E50/',e50Form,name='e50-view'),
    path('E60/',e60Form,name='e60-view'),
    path('jobprogress/',views.jobprogress,name='jobprogress'),
    path('myjobs/',views.myjobs,name='myjobs'),
    path('<workorder_id>/jobs/',views.workorder_jobs,name='workorder-jobs'),
    path('reports/',views.reports,name='reports'),
    path('e1/<e117_id>',views.generate_pdf,name='e1'),
    path('reinspection/',views.ReInspection,name='reinspection'),
    path('save_reinspection/',SaveReinspection.as_view(),name='save_reinspection'),
    path('close/<job_id>/',ApproveE117.as_view(),name='close-job'),
    path('reject/<job_id>/',views.reject_job,name='reject-job'),
    path('stations/<depot>/', Stations.as_view(),name="stations"),
    path('transformers/<depot>/',Transformers.as_view(),name="transformers"),
    path('approve', ApproveE50.as_view(),name="approve-e50"),
    path('approvee60', ApproveE60.as_view(),name="approve-e60"),
    path('viewreport',ViewReport.as_view(),name="viewreport"),
    path('all_centres/<centreparent>',ParentCentres.as_view(),name='all_centres/'),
    path('deleteworkorder/',views.delworkOrder,name='deleteworkorder/'),
    path("workorder_delete/",Worksdelete.as_view(),name="workorder_delete"),
    path("team/<team_leader>/<specialisation>/",TeamsByCentre.as_view(),name="workorder_delete"),
]

e117/urls.py
from django.urls import path, include
from .views import *
app_name = 'e117'

urlpatterns = [
    path('create/', SaveJob.as_view(), name='job-create')  
]

beweb/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Area(models.Model):
    area = models.CharField(max_length=50, null=True, unique=True)

    def __str__(self):
        return self.area


class Person(models.Model):
    name = models.CharField(max_length=100, verbose_name='full name')


class Employee(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    dob = models.DateField()

beweb/templates/beweb/layout.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="#" />
  <title>BE OPERATIONS</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'beweb/content/style.css'%}" />
  <link rel="stylesheet" type="text/css" href= "{% static 'beweb/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'beweb/css/font-awesome.min.css' %}" />
  <script src="{% static 'beweb/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'beweb/js/jquery.min.js' %}"></script>
  <script src="{% static 'beweb/js/jquery-ui.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'beweb/css/bootstrap.min.css' %}"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <style>
    body {
      height: 100%;
      font-family: Arial, Helvetica, sans-serif;
    }

    .dropdown-item>a {
      color: black;
    }

    /* Set a style for the submit button */
    .btn {
      background-color: #2B59A2;
      color: white;
      padding: 10px;
      border: none;
      cursor: pointer;
      width: 70%;
      opacity: 0.8;
      position: absolute;
      margin-left: 15px;
      margin-right: 15px;

    }

    .btn:hover {
      opacity: 1;
      color: #ffffff;
    }

    .custom-select {
      width: 50px !important;
    }
  </style>
</head>

<body>
  <!-- Navigation(Nav Bar) -->
  <nav class="navbar navbar-expand-md sticky-top" style="padding:35px 0px; display:flex;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="{%static 'beweb/img/belogo.png'%}" width="80" height="75" />
      </a>
      <a class="navbar-brand" href="#">
        <img src="{% static 'beweb/img/logo.png'%}" width="65" height="65" style="border-radius: 30px;" />
      </a>
    </div>
  </nav>
  <!-- Navigation(Nav Bar End)  -->
  <div class="bg">
    <!--Navbar -->
    <nav nav class="navbar navbar-expand-lg navbar-light" style="padding:25px;background-color:#FDF2E5;opacity:0.8;">
      <div class="container-fluid">
        <div class="dropdown">
          <a href="" id="imageDropdown" data-toggle="dropdown">
            <img src="{%static 'beweb/img/apps.png'%}" width="40" height="40" />
          </a>
          <div class="dropdown-menu">
            <button class="dropdown-item" type="button">
              <a tabindex="-1" href="#">Strategic Objectives</a>
            </button>
            <button class="dropdown-item" type="button">
              <a tabindex="-1" href="#">Processes and Procedures</a>
            </button>
            <button class="dropdown-item" type="button">
              <a tabindex="-1" href="{% url 'beweb:dashboard' %}">Business Applications</a>
            </button>
            <button class="dropdown-item" type="button">
              <a tabindex="-1" href="#">Competence Building</a>
            </button>
            <button class="dropdown-item" type="button">
              <a tabindex="-1" href="#">Engagement Forums</a>
            </button>
            <button class="dropdown-item" type="button">
              <a tabindex="-1" href="#">Knowledge Centre</a>
            </button>
            <button class="dropdown-item" type="button">
              <a tabindex="-1" href="{% url 'beweb:landing' %}">Dashboard</a>
            </button>
          </div>
        </div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active font-weight-bold" href="{% url 'beweb:dashboard' %}"
              id="workorders" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">WORK ORDERS</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'beweb:dashboard' %}">View</a>
            </div>
          </li>
          <li class="nav-item active">
            <a class="nav-link nav-brand font-weight-bold" href="{% url 'beweb:listjobs' %}">JOBS</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link nav-brand font-weight-bold" href="{% url 'beweb:view_teams' %}">TEAMS</a>

          </li>
          <li class="nav-item active">
            <a class="nav-link nav-brand font-weight-bold" href="{% url 'beweb:reports' %}">REPORTS</a>
          </li>

          <!-- <li class="nav-item active">
            <a class="nav-link nav-brand font-weight-bold " href="/beweb/myjobs/">MY JOBS</a>
          </li> -->



        </ul>
        <div class="collapse navbar-collapse w-100 order-3 dual-collapse2 " id="navbarTogglerDemo01">
          <a class="nav-link disabled">{% include 'beweb/loginpartial.html' %}</a>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <img src="{% static 'beweb/img/user.png'%}" style="margin-right:  10px" />
              <a class=" mr-sm-2 dropdown-toggle" data-toggle="dropdown">{{ user.first_name }} {{ user.last_name }} <b
                  class="caret"></b></a>
              <!-- <i class="fa fa-ellipsis-v" aria-hidden="true"></i> -->
              <ul class="dropdown-menu dropdown-menu-right" role="menu">
                <a class="dropdown-item" href="#">View Profile</a>
                <a class="dropdown-item" href="{% url 'password_reset' %}">Change Password</a>
                <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
  </div>
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <!--/.Navbar -->
  <script>
    $("#leader").on("click change", function (e) {
      /// $("#output").html("Event type: " + e.target.nodeName);

      var e = document.getElementById("leader");
      var strUser = e.options[e.selectedIndex].value;
      $("#data").html("Selected :" + strUser);
    });
    $("#select_all").click(function () {
      $("#ms option").prop("selected", true);
    });
  </script>

  {% block scripts %}{% endblock %}
</body>

</html>

beweb/templates/beweb/wo.html
{% extends "beweb/layout.html" %} {% block content %}


<canvas></canvas>
<h6 hidden>Artisan</h6>
<ul hidden>
    <li>{{data.descr}}</li>
    <!-- <li>{{data.specialisation}}</li> -->
    <li>{{data.username}}</li>
    <!-- <li>{{data.center}}</li> -->
    <li>{{data.section}} </li>
</ul>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    <form action="{% url 'beweb:getteam' %}" method="GET">
                        {% csrf_token %}
                        <label for="sel1">
                            <h6>Select Team Leader:</h6>
                        </label>
                        <select class="form-control col-md-12" id="leader" name="leader">
                            <option selected="selected">
                                {{tl}}
                            </option>
                            {% for tl in team_leaders %}
                            <option>{{tl}}</option>
                            {% endfor %}
                        </select>

                        <input type="submit" class="btn btn-sm btn-primary" value="Get Team" />
                    </form>
                    <hr />
                   
                </div>
                <div class="col-md-6">

                </div>

            </div>

        </div>
        <div class="col-md-6">
         <form action="{% url 'beweb:getteam' %}" method="POST">
                      {% csrf_token %}

            <h6>Team Members</h6>
            <input type="button" class="form-control btn-sm" id="select_all" name="select_all" value="Select All">
           
            <select multiple="multiple"  name="members" id="members" size="5">
    {% for tm in my_teams %}
        <option value="{{tm}}">{{tm}}</option>
    {% endfor %}
</select>
  
                        <input type="submit" class="btn btn-sm btn-success" value="Save Data" />
                    </form>
        </div>
        <div class="col-md-4">


            <hr />

            <div id="data"></div>
        </div>
    </div>
</div>

{% endblock %}