BEOperations/urls.py
from django.contrib import admin

from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from beweb import forms, views
from datetime import datetime
from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', views.home, name='home'),
    path('api-token-auth/', obtain_auth_token,
         name='api_token_auth'),  # <-- And here
    path('beapi/', include('beapi.urls', namespace='beapi')),
    path('beweb/', include('beweb.urls', namespace='beweb')),
    # path('e117/', include('e117.urls', namespace='e117')),
    path('login/',
         LoginView.as_view
         (
             template_name='beweb/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context={
                 'note': 'Log in',
                 'title': 'Log in',
                 'year': datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),
    path('admin/', admin.site.urls, name="admin"),
    path('api-auth', include('rest_framework.urls')),
    url('^', include('django.contrib.auth.urls')),
    # url(r'^report_builder/', include('report_builder.urls'))
    # url(r'^api-token-auth/', obtain_auth_token)
]

beweb/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . forms import *
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from graphene_django.views import GraphQLView
from .views import *
app_name = 'beweb'

urlpatterns = [
    path('graphql', GraphQLView.as_view( graphiql=True)),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('landing', views.landing, name='landing'),
    path('jobs',views.viewJobs,name='jobs'),
    path('listjobs/',ListJobs.as_view(),name='listjobs'),
    path('sjob',views.seejob,name='sjob'),
    path('editjob/',views.editjob,name='editjob'),
    # path('reassignjob/',views.reassignjob,name='reassignjob'),
    path('changejob/',views.ChangeJob.as_view(),name='changejob'),
    path('job/reassign/',views.JobReassign.as_view(),name='job/reassign'),
    path('job/',views.job,name='job'),
    path('mywork/', workorder, name='mywork'),
    path('api/login', views.login),
    path('addjob/', AddJob.as_view(), name='addjob'),
    path('getteam/', MyTeam.as_view(), name='getteam'),
    path('getmyteam/', MTeam.as_view(), name='getmyteam'),
    path('getasset/', MyAsset.as_view(), name='getasset'),
    path('updatejobasset/', MyjobAsset.as_view(), name='updatejobasset'),
    path('getwoid/', Mywo.as_view(), name='getwoid'),
    path('save/asset/', SaveJobandAddAsset.as_view(), name='SaveJobandAddAsset'),
    path('save/job/', SaveJob.as_view(), name='SaveJob'),
    path('create/e117/', SaveE117Job.as_view(), name='e117-create'),  
    path('saveasset/', WoSaveAsset.as_view(), name='saveasset'),
    path('get_user/', views.get_user, name='get_user'),
    path('addteam/', views.addteam, name='addteam'),
    path('create/', views.create, name='create'),
    path('create_e117/',Create_E117_Job.as_view(),name='create_e117'),
    path('newteam/', views.create_team, name='newteam'),
    path('view_teams/',views.view_Teams,name='view_teams'),
    path('team/<ec_number>',views.view_Team,name='team'),
    path('editteam/',views.editTeam,name='editteam'),  
    path('orders/<ec_num>/', JobsViewSet.as_view(),name="orders"),
    path('openjobs/<username>/<section>/<status>/', JobsViewProcedure.as_view(),name="openjobs"),
    path('progressjobs/<username>/<section>/<status>/', ProgressJobs.as_view(), name="progressjobs"),
    path('jobsreport/<jobtype>/<centre>/<status>/<start_date>/<end_date>/',JobsReports.as_view(),name="jobsreport"),
    path('workorders_report/<workorder_centre>/<workorder_status>/<workorder_start_date>/<workorder_end_date>/',WorkordersReports.as_view(),name="workorders_report"),
    path('rejectedjobs/', ReinspectionJobs.as_view(), name="rejectedjobs"),
    path('supervisorjobs/<username>/<section>/<status>/', SuspendedJobs.as_view(),name="supervisorjobs"),
    path('workorders/<centre>/',WorkorderViewSet.as_view(),name='workorders'),
    path('save/workorder/', OnlySaveWorkorder.as_view(), name='saveworkorder'),
    path('editwork/', editwork, name='editwork'),
    path('edit/', SaveEditedWorkorder.as_view(), name='saveeditedworkorder'),
    path('form/<job_id>/', FormsView.as_view(), name='form'),
    path('Jobworkflow/', views.Job_workflow, name='Jobworkflow'),
    path('forms/', views.listForms, name='forms'),
    path('display/e84/',views.displayE84Form,name='e84-display'),
    path('E117/',views.e117Form,name='e117-display'),
    path('E84/',e84Form,name='e84-view'),
    path('E50/',e50Form,name='e50-view'),
    path('E60/',e60Form,name='e60-view'),
    path('jobprogress/',views.jobprogress,name='jobprogress'),
    path('myjobs/',views.myjobs,name='myjobs'),
    path('<workorder_id>/jobs/',views.workorder_jobs,name='workorder-jobs'),
    path('reports/',views.reports,name='reports'),
    path('e1/<e117_id>',views.generate_pdf,name='e1'),
    path('reinspection/',views.ReInspection,name='reinspection'),
    path('save_reinspection/',SaveReinspection.as_view(),name='save_reinspection'),
    path('close/<job_id>/',ApproveE117.as_view(),name='close-job'),
    path('reject/<job_id>/',views.reject_job,name='reject-job'),
    path('stations/<depot>/', Stations.as_view(),name="stations"),
    path('transformers/<depot>/',Transformers.as_view(),name="transformers"),
    path('approve', ApproveE50.as_view(),name="approve-e50"),
    path('approvee60', ApproveE60.as_view(),name="approve-e60"),
    path('viewreport',ViewReport.as_view(),name="viewreport"),
    path('all_centres/<centreparent>',ParentCentres.as_view(),name='all_centres/'),
    path('deleteworkorder/',views.delworkOrder,name='deleteworkorder/'),
    path("workorder_delete/",Worksdelete.as_view(),name="workorder_delete"),
    path("team/<team_leader>/<specialisation>/",TeamsByCentre.as_view(),name="workorder_delete"),
]

e117/urls.py
from django.urls import path, include
from .views import *
app_name = 'e117'

urlpatterns = [
    path('create/', SaveJob.as_view(), name='job-create')  
]

beweb/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Area(models.Model):
    area = models.CharField(max_length=50, null=True, unique=True)

    def __str__(self):
        return self.area


class Person(models.Model):
    name = models.CharField(max_length=100, verbose_name='full name')


class Employee(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    dob = models.DateField()

beweb/views.py
import requests
from django.contrib.auth.models import User
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.shortcuts import render, render_to_response,redirect
from django.http import HttpRequest, HttpResponseRedirect
from django.http import HttpResponse
from formtools.wizard.views import SessionWizardView
from django.core.mail import send_mail
import operator
from beapi.models import *
from .forms import *
import json 
import uuid
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import authenticate
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND, HTTP_200_OK)
from rest_framework.response import Response
from django.contrib.auth.models import User
import posixpath
import os
import random
from . forms import NameForm, WorkOrderForm, JobForm, GeneralForm
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django_tables2 import RequestConfig
from .tables import *
from rest_framework import viewsets
from beapi.serializers import *
from django.db.models import Q
from django.db import connection
from . beglobals import *
#graphQl Queries link
from .graphqlqueries import schema


# LIBRARIES FOR generating PDF
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
#
from django.core.mail import EmailMessage


def user_authenticate(username):
    users = User.objects.all()
    for user in users:
        if user.username == username:
            token, created = Token.objects.get_or_create(user=user)
            return user.username, token.key
    return None


@csrf_exempt
@api_view(["POST"])
@permission_classes((AllowAny,))
def login(request):
    username = request.data.get("username")
    password = request.data.get("password")
    if username is None or password is None:
        return Response({'error': 'Please provide both username and password'},
                        status=HTTP_400_BAD_REQUEST)
    user = authenticate(username=username, password=password)
    if not user:
        return Response({'error': 'Invalid Credentials'},
                        status=HTTP_404_NOT_FOUND)
    token, _ = Token.objects.get_or_create(user=user)
    return Response({'token': token.key},
                    status=HTTP_200_OK)


def execsys(ecnum):
    URL = "http://" + beserver + ":8082/users/username/" + ecnum
    r = requests.get(url=URL)
    data = r.json()

    return data


def get_center(centre_code):
    if centre_code == "ER":
        centre = "Regional Office (ER)"
        return centre, centre_code
    if centre_code == "ERM":
        centre = "Eastern Maintenance"
        return centre, centre_code
    if centre_code == "END":
        centre = "Network Development"
        return centre, centre_code
    if centre_code == "MTD":
        centre = "Mutare District"
        return centre, centre_code
    if centre_code == "URB":
        centre = "Mutare Urban"
        return centre, centre_code
    if centre_code == "ENV":
        centre = "Mutare Environs"
        return centre, centre_code
    if centre_code == "MTG":
        centre = "Mutare Garage"
        return centre, centre_code
    if centre_code == "MND":
        centre = "Manicaland District"
        return centre, centre_code
    if centre_code == "NYA":
        centre = "Nyanga"
        return centre, centre_code
    if centre_code == "RSP":
        centre = "Rusape"
        return centre, centre_code
    if centre_code == "CHP":
        centre = "Chipinge"
        return centre, centre_code
    if centre_code == "CHM":
        centre = "Chimanimani"
        return centre, centre_code
    if centre_code == "MSB":
        centre = "Middle Sabi"
        return centre, centre_code
    if centre_code == "MSD":
        centre = "Masvingo District"
        return centre, centre_code
    if centre_code == "MSV":
        centre = "Masvingo Urban"
        return centre, centre_code
    if centre_code == "GUT":
        centre = "Gutu"
        return centre, centre_code
    if centre_code == "MAS":
        centre = "Mashava"
        return centre, centre_code
    if centre_code == "RUT":
        centre = "Rutenga"
        return centre, centre_code
    if centre_code == "CHR":
        centre = "Chiredzi"
        return centre, centre_code
    if centre_code == "MSG":
        centre = "Masvingo Garage"
        return centre, centre_code
    centre = "No Centre"
    centre_code = "No Centre Code"
    return centre, centre_code


class MyTeam(View):
    def get(self, request, *args, **kwargs):
        team_leaders = request.GET['leader']
        myteam, teams = artisan_team(team_leaders)
        data = ""
        team_leaders = []
        Teams = Team.objects.all()
        my_teams = dict()

        for teamleader in Teams:
            if teamleader.team_leader not in [member.team_leader for member in team_leaders]:
                team_leaders.append(teamleader)
                my_teams[teamleader.team_leader] = []

        for teamleader in team_leaders:
            teammembers = Team.objects.filter(team_leader=teamleader)
            if teammembers:
                for teammember in teammembers:
                    my_teams[teamleader.team_leader].append(
                        teammember.team_member)
        return render(request, 'beweb/wo.html', {
            'data': data, 'myteam': myteam, 'my_teams': my_teams, 'teams': teams, 'team_leaders': team_leaders
        })

    def post(self, request, *args, **kwargs):
        members = []
        members = request.POST.getlist('members')
        return HttpResponse('Are you sure you want to save data')


class MTeam(View):
    def get(self, request, *args, **kwargs):
        data = execsys(request.user.username)
        centre_code = data['section']
        username = data['username']
        centre, centre_code = get_center(centre_code)
        centre = request.GET['centre']
        date = datetime.now().strftime("%Y%m%d%H%M")
        centre_code = request.GET['centre_code']
        team_leaders = request.GET['leader']
        myteam = artisan_team(team_leaders)
        data = ""
        return render(request, 'beweb/job/create.html', {
            'data': data, 'myteam': myteam,  'team_leaders': team_leaders
        })


class MyAssets(View):
    def get(self, request, *args, **kwargs):
        data = execsys(request.user.username)
        centre = data['section']
        return render(request, 'beweb/assets.html', {'centre': centre
                                                     })


class WoSaveAsset(View):
    def post(self, request, *args, **kwargs):
        reference_number = None
        # IF WORKORDER DOES NOT EXIST, create workorder first
        assignee = request.session['assignee']
        team_members =request.session['teammembers']
        fleet = request.session['fleet']
        if request.session['workorder_exist'] == False:
            username = request.session['username']
            description = request.session['description']
            supervisor = request.session['username']
            data = execsys(request.user.username)
            centre = data['section']
            section = request.session['section']
            centre_code = data['section']
            work_order_id = request.session['work_order']
            date = datetime.now().strftime("%Y%m%d%H%M")
            createdby = request.session['username']
            wo = request.session['work_order']
            job_description = request.session['job_description']
            expected_end_dt = request.session['expected_end_dt']
            section = request.session['section']
            job_number = request.session['job_number']
            trigger = request.session['trigger']
            start_date = request.session['start_date']
            asset_type = request.session['asset_type']
            job_type = request.session['job_type_id']
           

     
      
            if 'E50' in job_type:
                asset_id = request.POST['asset_id']
                asset_name = ''
                asset_number = ''
                asset_serial = ''
                e50_id = e50_id = "E50"+datetime.now().strftime("%Y%m%d%H%M") + \
                    str(random.randrange(000000, 100000))
                station_id = request.POST['asset_id']
            else:
                asset_id = None
                asset_name = None
                asset_number = None
                asset_serial = None

            if 'E60' in job_type:
                asset_id = request.POST['asset_id']
                district = data['centre']
                asset_name = ''
                asset_number = ''
                asset_serial = ''
                e60_id = e60_id = "E60"+datetime.now().strftime("%Y%m%d%H%M") + \
                    str(random.randrange(000000, 100000))
                transformer_id = request.POST['asset_id']
                work_type = request.POST['work_type']
            else:
                asset_id = None
                asset_name = None
                asset_number = None
                asset_serial = None

            wo = save_wo(username, description, supervisor,
                         centre, date, centre_code, work_order_id)
            joid = Save_Job(createdby, assignee, job_type, wo, job_description, expected_end_dt, centre,
                            section, job_number, trigger, start_date, asset_type, reference_number, asset_id)
             
            if 'E50' in job_type:
                save_e50(e50_id, job_number, createdby, station_id)
            else:

beweb/templates/beweb/reports/e84_details.html
{% extends "beweb/dashboard.html" %}
{% block content %}
 {% if user.is_authenticated %} 
 {% load render_table from django_tables2 %}
    <br />

    <div class="container col-md-12">
    <form action="{% url 'beweb:Aprove' %}" method="get">
    <div class="row">
            
            <div class="col-md-10">
                <div class="row">

                    <div class="col-md-10">
                    <br>  <h4 class="bg-dark text-light text-center">
                            E84 General
                          </h4>
                        {% render_table E84_general %}
                      </div >  <div class="col-md-10">
                    <br>  <h4 class="bg-dark text-light text-center">
                            E84 Form
                        </h4>
                        {% render_table E84_table %}
                      </div >
                    
                  
                  
                  
                      <br>  <div class="  d-flex justify-content-center col-md-10">
                          <input class="btn btn-sm btn-dark  btn-round text-success" type="submit" value="Aprove"name="Add Job">
                          <input class="btn btn-sm btn-dark  btn-round text-danger" type="submit" value="reject"name="Add Job">
                          <input class="btn btn-sm btn-dark  btn-round text-info" type="submit" value="recomment"name="Add Job">
                          <input class="btn btn-sm btn-dark  btn-round text-warning" type="submit" value="Suspend"name="Add Job">
                    </div>
                </div>
            </div>
        </div>
    </form>


    </div>

 {% endif %}
 {% endblock %}

beweb/templates/beweb/reports/job_details.html
{% extends "beweb/dashboard.html" %}{% block content %} {% if user.is_authenticated %} {% load render_table from django_tables2 %}
<br />

<div class="container col-md-12">
<form action="{% url 'beweb:addjob' %}" method="get">
<div class="row">
        <div class="col-md-2">
            <div class="row">



                <div class="col-md-12">
            {% csrf_token %}
                    <h2 class="bg-dark text-light text-center">
                     
                                        {{Workorder_selected}}
</h2>
                   
                    
                </div>
              
            </div>
        </div>
        <div class="col-md-10">
            <div class="row">


                <div class="col-md-10">
                    <h4 class="bg-dark text-light text-center">
                        Jobs 
                       <input value="{{Workorder_selected.work_order_id}}" hidden name="wo" id="wo" />
                      
                            </i></button>
                
                    </h4>
                    {% render_table job_table %}
                </div>
               
                <div class="col-md-10">
                    <h4 class="bg-dark text-light text-center">
                        Assistant Members
                    </h4>
                    <table class="table">
                        <thead class="text-justify">
                            <tr>
                                <th>Team Member</th>
                                <th>Start Date</th>
                              </tr>
                        </thead>
                        <tbody> {% for jp in my_progress %} {% for tm in my_team %} {% if jp == tm.job_progress%}
                            <tr>

                                <td>{{tm.ec_num}}</td>
                                <td>{{tm.start_dt}}</td>
                               
                            </tr>
                            {% endif%} {% endfor %} {% endfor %}

                        </tbody>
                    </table>
                </div>
                 <div class="col-md-10">
                    <h4 class="bg-dark text-light text-center">
                        Job Progress 
                   
                    </h4>
                    {% render_table jobp_table %}
                </div>
                 <div class="col-md-10">
                <br>  <h4 class="bg-dark text-light text-center">
                        E84 General
                      </h4>
                    {% render_table E84_general %}
                  </div >  <div class="col-md-10">
                <br>  <h4 class="bg-dark text-light text-center">
                        E84 Form
                    </h4>
                    {% render_table E84_table %}
                  </div >
                 
               
               
               
                <div class="container">
                  <div class="col-md-6">
                      <input class="btn btn-sm btn-dark btn-block btn-round text-info" type="submit" value="Add Job"name="Add Job">
                </div>
                </div>
            </div>
        </div>
    </div>
</form>


</div> {% endif %} {% endblock %}s

beweb/templates/beweb/reports/view_report.html
<!DOCTYPE html>
{% extends "beweb/layout.html" %} {% load i18n%} {% block content %} {% if user.is_authenticated %}
{%load staticfiles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .fa-stack {
        position: relative;
        color: #2B59A2;
        /* color: lightgreen; */
    }
</style>

<body>
            <div class="container" style="background-color:#f4f4f4;margin-top:50px;border-radius:15px;" id="job_report">
                <br>
                <h3 class="text-center font-weight-bold">Jobs Reports</h3>
                <table class="w3-table thead-dark w3-border table table-striped table-bordered display"
                    data-ajax="/beweb/jobsreport/{{jobtype}}/{{centre_code}}/{{status}}/{{start_date}}/{{end_date}}/?format=datatables" data-server-side="false"
                    id="jobs" style="background-color:#f4f4f4;border-radius: 5px;width:100%">
                    <thead>
                        <tr>
                            <th style="color:black" id="work_order">Workorder Number</th>
                            <th style="color:black" id="job_number">Job Number</th>
                            <th style="color:black" id="description">Description</th>
                            <th style="color:black" id="date_created"> Date Created</th>
                            <th style="color:black" id="date_ended"> Date Closed</th>
                            <th style="color:black" id="status">Status</th>
                            <th style="color:black" id="forms">Forms</th>
                        </tr>
                    </thead>
                </table>
            </div>
        <div class="container" style="background-color:#f4f4f4;margin-top:50px;border-radius:15px;" id="workorder_report">
            <br>
            <h3 class="text-center font-weight-bold">WORK ORDERS REPORTS</h3>
            <table class="w3-table thead-dark w3-border table table-striped table-bordered display"
                data-server-side="false" data-ajax="/beweb/workorders_report/{{centre_code}}/{{status}}/{{start_date}}/{{end_date}}/?format=datatables" id="workord"
                style="background-color:#f4f4f4;border-radius: 5px">
                <thead>
                    <tr>
                        <th style="color: black;" id="workorder">Work Order Number</th>
                        <th style="color: black;" id="wo_description">Description</th>
                        <th style="color: black;" id="wo_date_created">Date Created</th>
                        <th style="color: black;" id="wo_jobs">Job(s)</th>
                        <th style="color: black;" id="wo_status">Status</th>
                    </tr>
                </thead>
            </table>
        </div>


    <script type="text/javascript" src="{% static 'beweb/DataTables/datatables.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'beweb/DataTables/datatables.min.css' %}" />
    <script>
        $(document).ready(function () {
            var reportype= "{{report_type}}"
            var pagetype = "{{pagetype}}"
            sessionStorage.setItem("type_of_page", pagetype);
            alert(pagetype)
            if (reportype==='jobs'){
                $('#workorder_report').hide()
                $('#job_report').show()
                var table= $('#jobs').DataTable({
                    "ajax": '/beweb/jobsreport/{{jobtype}}/{{centre}}/{{status}}/{{start_date}}/{{end_date}}/?format=datatables',
                "serverSide": true,
                "columns": [
                    { "data": "work_order_id", "searchable": false },
                    {
                        "data": "job_id", "searchable": true,
                        "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                            $(nTd).html("<a data-toggle='collapse' href='#" + oData.job_id + "' aria-expanded='false' aria-controls='" + oData.job_id + "'>" + oData.job_id + "</a><div class='card card-body collapse' id='" + oData.job_id + "'><a class='row' href='/beweb/job/?q=" + oData.job_id + "'>View</a><a class='row' href='/beweb/editjob/?q=" + oData.job_id + "'>Edit</a></div>");
                        }
                    },
                    { "data": "description", "searchable": true },
                    { "data": "created_on", "searchable": true },
                    { "data": "end_dt", "searchable": true },
                    { "data": "status", "searchable": false },
                    {
                        "data": "form_id", "searchable": false,
                        "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                            $(nTd).html("<a href='/beweb/forms/?job_id=" + oData.job_id + "&type= {{reports}}" + "'>" + oData.number_of_forms + "</a>");
                        }
                    }
                ]
                });
            }
            else if (reportype=="workorder"){

                $('#workorder_report').show()
                $('#job_report').hide()

                var table1 = $('#workord').DataTable({
                    "ajax": '/beweb/workorders_report/{{centre_code}}/{{status}}/{{start_date}}/{{end_date}}/?format=datatables',
                "serverSide": true,
                "columns": [
                    {
                        "data": "work_order_id", "searchable": true,
                        "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                            $(nTd).html("<a data-toggle='collapse' href='#" + oData.work_order_id + "' aria-expanded='false' aria-controls='" + oData.work_order_id + "'>" + oData.work_order_id + "</a><div class='card card-body collapse' id='" + oData.work_order_id + "'><a class='row' href='/beweb/mywork/?q=" + oData.work_order_id + "'>View</a><a class='row' href='/beweb/editwork/?q=" + oData.work_order_id + "'>Edit</a><a class='row' href='/beweb/addjob/?q=" + oData.work_order_id + "'>Add Job</a></div>");
                        }
                    },
                    { "data": "description", "searchable": true },
                    { "data": "created_on", "searchable": true },
                    { "data": "no_of_jobs", "searchable": false },
                    { "data": "workorderstatus", "searchable": false }
                    ]
                
                });
            }
           
           
        });
    </script>
</body>
{% endif %} {% endblock %}

beweb/templates/beweb/reports/work_detail.html
{% extends "beweb/dashboard.html" %}{% block content %} {% if user.is_authenticated %} {% load render_table from django_tables2 %}
<br />
<div class="container col-md-10">
    <hr />
    <h5>

        <a href="{% url 'beweb:mywork' %}">
            <button class="collapse-item btn btn-sm shadow-lg btn-primary"><i class="fas fa-fw fa-list"></i> Work Orders
            </button> </a>
        <hr />
        <div class="alert alert-success" role="alert">
            Action completed successfully !!
        </div>
    </h5>
    <div class="row">
        <div class="col-md-4">
            <h4 class="bg-dark text-light text-center">
                Work Order
            </h4>{% render_table workorder_table %}
        </div>

        <div class="col-md-8">

            <h4 class="bg-dark text-light text-center">
                Created Jobs
            </h4>
            {% render_table job_table %}
        </div>
        <div class="col-md-12">

            <h4 class="bg-dark text-light text-center">
                Form Created
            </h4>
            {% render_table E84_table %}

        </div>
        <div class="col-md-6">

            <h4 class="bg-dark text-light text-center">
                Job Progress:
            </h4>
            {% render_table jobp_table %}
        </div>
        <div class="col-md-6">

            <h4 class="bg-dark text-light text-center">
                Job Assigned To :
            </h4>
            {% render_table team_table %}
        </div>

    </div>
</div>


{% endif %} {% endblock %}