BEOperations/urls.py
from django.contrib import admin

from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from beweb import forms, views
from datetime import datetime
from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', views.home, name='home'),
    path('api-token-auth/', obtain_auth_token,
         name='api_token_auth'),  # <-- And here
    path('beapi/', include('beapi.urls', namespace='beapi')),
    path('beweb/', include('beweb.urls', namespace='beweb')),
    # path('e117/', include('e117.urls', namespace='e117')),
    path('login/',
         LoginView.as_view
         (
             template_name='beweb/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context={
                 'note': 'Log in',
                 'title': 'Log in',
                 'year': datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),
    path('admin/', admin.site.urls, name="admin"),
    path('api-auth', include('rest_framework.urls')),
    url('^', include('django.contrib.auth.urls')),
    # url(r'^report_builder/', include('report_builder.urls'))
    # url(r'^api-token-auth/', obtain_auth_token)
]

beweb/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . forms import *
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from graphene_django.views import GraphQLView
from .views import *
app_name = 'beweb'

urlpatterns = [
    path('graphql', GraphQLView.as_view( graphiql=True)),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('landing', views.landing, name='landing'),
    path('jobs',views.viewJobs,name='jobs'),
    path('listjobs/',ListJobs.as_view(),name='listjobs'),
    path('sjob',views.seejob,name='sjob'),
    path('editjob/',views.editjob,name='editjob'),
    # path('reassignjob/',views.reassignjob,name='reassignjob'),
    path('changejob/',views.ChangeJob.as_view(),name='changejob'),
    path('job/reassign/',views.JobReassign.as_view(),name='job/reassign'),
    path('job/',views.job,name='job'),
    path('mywork/', workorder, name='mywork'),
    path('api/login', views.login),
    path('addjob/', AddJob.as_view(), name='addjob'),
    path('getteam/', MyTeam.as_view(), name='getteam'),
    path('getmyteam/', MTeam.as_view(), name='getmyteam'),
    path('getasset/', MyAsset.as_view(), name='getasset'),
    path('updatejobasset/', MyjobAsset.as_view(), name='updatejobasset'),
    path('getwoid/', Mywo.as_view(), name='getwoid'),
    path('save/asset/', SaveJobandAddAsset.as_view(), name='SaveJobandAddAsset'),
    path('save/job/', SaveJob.as_view(), name='SaveJob'),
    path('create/e117/', SaveE117Job.as_view(), name='e117-create'),  
    path('saveasset/', WoSaveAsset.as_view(), name='saveasset'),
    path('get_user/', views.get_user, name='get_user'),
    path('addteam/', views.addteam, name='addteam'),
    path('create/', views.create, name='create'),
    path('create_e117/',Create_E117_Job.as_view(),name='create_e117'),
    path('newteam/', views.create_team, name='newteam'),
    path('view_teams/',views.view_Teams,name='view_teams'),
    path('team/<ec_number>',views.view_Team,name='team'),
    path('editteam/',views.editTeam,name='editteam'),  
    path('orders/<ec_num>/', JobsViewSet.as_view(),name="orders"),
    path('openjobs/<username>/<section>/<status>/', JobsViewProcedure.as_view(),name="openjobs"),
    path('progressjobs/<username>/<section>/<status>/', ProgressJobs.as_view(), name="progressjobs"),
    path('jobsreport/<jobtype>/<centre>/<status>/<start_date>/<end_date>/',JobsReports.as_view(),name="jobsreport"),
    path('workorders_report/<workorder_centre>/<workorder_status>/<workorder_start_date>/<workorder_end_date>/',WorkordersReports.as_view(),name="workorders_report"),
    path('rejectedjobs/', ReinspectionJobs.as_view(), name="rejectedjobs"),
    path('supervisorjobs/<username>/<section>/<status>/', SuspendedJobs.as_view(),name="supervisorjobs"),
    path('workorders/<centre>/',WorkorderViewSet.as_view(),name='workorders'),
    path('save/workorder/', OnlySaveWorkorder.as_view(), name='saveworkorder'),
    path('editwork/', editwork, name='editwork'),
    path('edit/', SaveEditedWorkorder.as_view(), name='saveeditedworkorder'),
    path('form/<job_id>/', FormsView.as_view(), name='form'),
    path('Jobworkflow/', views.Job_workflow, name='Jobworkflow'),
    path('forms/', views.listForms, name='forms'),
    path('display/e84/',views.displayE84Form,name='e84-display'),
    path('E117/',views.e117Form,name='e117-display'),
    path('E84/',e84Form,name='e84-view'),
    path('E50/',e50Form,name='e50-view'),
    path('E60/',e60Form,name='e60-view'),
    path('jobprogress/',views.jobprogress,name='jobprogress'),
    path('myjobs/',views.myjobs,name='myjobs'),
    path('<workorder_id>/jobs/',views.workorder_jobs,name='workorder-jobs'),
    path('reports/',views.reports,name='reports'),
    path('e1/<e117_id>',views.generate_pdf,name='e1'),
    path('reinspection/',views.ReInspection,name='reinspection'),
    path('save_reinspection/',SaveReinspection.as_view(),name='save_reinspection'),
    path('close/<job_id>/',ApproveE117.as_view(),name='close-job'),
    path('reject/<job_id>/',views.reject_job,name='reject-job'),
    path('stations/<depot>/', Stations.as_view(),name="stations"),
    path('transformers/<depot>/',Transformers.as_view(),name="transformers"),
    path('approve', ApproveE50.as_view(),name="approve-e50"),
    path('approvee60', ApproveE60.as_view(),name="approve-e60"),
    path('viewreport',ViewReport.as_view(),name="viewreport"),
    path('all_centres/<centreparent>',ParentCentres.as_view(),name='all_centres/'),
    path('deleteworkorder/',views.delworkOrder,name='deleteworkorder/'),
    path("workorder_delete/",Worksdelete.as_view(),name="workorder_delete"),
    path("team/<team_leader>/<specialisation>/",TeamsByCentre.as_view(),name="workorder_delete"),
]

e117/urls.py
from django.urls import path, include
from .views import *
app_name = 'e117'

urlpatterns = [
    path('create/', SaveJob.as_view(), name='job-create')  
]

beweb/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Area(models.Model):
    area = models.CharField(max_length=50, null=True, unique=True)

    def __str__(self):
        return self.area


class Person(models.Model):
    name = models.CharField(max_length=100, verbose_name='full name')


class Employee(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    dob = models.DateField()

beweb/views.py
import requests
from django.contrib.auth.models import User
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.shortcuts import render, render_to_response,redirect
from django.http import HttpRequest, HttpResponseRedirect
from django.http import HttpResponse
from formtools.wizard.views import SessionWizardView
from django.core.mail import send_mail
import operator
from beapi.models import *
from .forms import *
import json 
import uuid
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import authenticate
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND, HTTP_200_OK)
from rest_framework.response import Response
from django.contrib.auth.models import User
import posixpath
import os
import random
from . forms import NameForm, WorkOrderForm, JobForm, GeneralForm
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django_tables2 import RequestConfig
from .tables import *
from rest_framework import viewsets
from beapi.serializers import *
from django.db.models import Q
from django.db import connection
from . beglobals import *
#graphQl Queries link
from .graphqlqueries import schema


# LIBRARIES FOR generating PDF
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
#
from django.core.mail import EmailMessage


def user_authenticate(username):
    users = User.objects.all()
    for user in users:
        if user.username == username:
            token, created = Token.objects.get_or_create(user=user)
            return user.username, token.key
    return None


@csrf_exempt
@api_view(["POST"])
@permission_classes((AllowAny,))
def login(request):
    username = request.data.get("username")
    password = request.data.get("password")
    if username is None or password is None:
        return Response({'error': 'Please provide both username and password'},
                        status=HTTP_400_BAD_REQUEST)
    user = authenticate(username=username, password=password)
    if not user:
        return Response({'error': 'Invalid Credentials'},
                        status=HTTP_404_NOT_FOUND)
    token, _ = Token.objects.get_or_create(user=user)
    return Response({'token': token.key},
                    status=HTTP_200_OK)


def execsys(ecnum):
    URL = "http://" + beserver + ":8082/users/username/" + ecnum
    r = requests.get(url=URL)
    data = r.json()

    return data


def get_center(centre_code):
    if centre_code == "ER":
        centre = "Regional Office (ER)"
        return centre, centre_code
    if centre_code == "ERM":
        centre = "Eastern Maintenance"
        return centre, centre_code
    if centre_code == "END":
        centre = "Network Development"
        return centre, centre_code
    if centre_code == "MTD":
        centre = "Mutare District"
        return centre, centre_code
    if centre_code == "URB":
        centre = "Mutare Urban"
        return centre, centre_code
    if centre_code == "ENV":
        centre = "Mutare Environs"
        return centre, centre_code
    if centre_code == "MTG":
        centre = "Mutare Garage"
        return centre, centre_code
    if centre_code == "MND":
        centre = "Manicaland District"
        return centre, centre_code
    if centre_code == "NYA":
        centre = "Nyanga"
        return centre, centre_code
    if centre_code == "RSP":
        centre = "Rusape"
        return centre, centre_code
    if centre_code == "CHP":
        centre = "Chipinge"
        return centre, centre_code
    if centre_code == "CHM":
        centre = "Chimanimani"
        return centre, centre_code
    if centre_code == "MSB":
        centre = "Middle Sabi"
        return centre, centre_code
    if centre_code == "MSD":
        centre = "Masvingo District"
        return centre, centre_code
    if centre_code == "MSV":
        centre = "Masvingo Urban"
        return centre, centre_code
    if centre_code == "GUT":
        centre = "Gutu"
        return centre, centre_code
    if centre_code == "MAS":
        centre = "Mashava"
        return centre, centre_code
    if centre_code == "RUT":
        centre = "Rutenga"
        return centre, centre_code
    if centre_code == "CHR":
        centre = "Chiredzi"
        return centre, centre_code
    if centre_code == "MSG":
        centre = "Masvingo Garage"
        return centre, centre_code
    centre = "No Centre"
    centre_code = "No Centre Code"
    return centre, centre_code


class MyTeam(View):
    def get(self, request, *args, **kwargs):
        team_leaders = request.GET['leader']
        myteam, teams = artisan_team(team_leaders)
        data = ""
        team_leaders = []
        Teams = Team.objects.all()
        my_teams = dict()

        for teamleader in Teams:
            if teamleader.team_leader not in [member.team_leader for member in team_leaders]:
                team_leaders.append(teamleader)
                my_teams[teamleader.team_leader] = []

        for teamleader in team_leaders:
            teammembers = Team.objects.filter(team_leader=teamleader)
            if teammembers:
                for teammember in teammembers:
                    my_teams[teamleader.team_leader].append(
                        teammember.team_member)
        return render(request, 'beweb/wo.html', {
            'data': data, 'myteam': myteam, 'my_teams': my_teams, 'teams': teams, 'team_leaders': team_leaders
        })

    def post(self, request, *args, **kwargs):
        members = []
        members = request.POST.getlist('members')
        return HttpResponse('Are you sure you want to save data')


class MTeam(View):
    def get(self, request, *args, **kwargs):
        data = execsys(request.user.username)
        centre_code = data['section']
        username = data['username']
        centre, centre_code = get_center(centre_code)
        centre = request.GET['centre']
        date = datetime.now().strftime("%Y%m%d%H%M")
        centre_code = request.GET['centre_code']
        team_leaders = request.GET['leader']
        myteam = artisan_team(team_leaders)
        data = ""
        return render(request, 'beweb/job/create.html', {
            'data': data, 'myteam': myteam,  'team_leaders': team_leaders
        })


class MyAssets(View):
    def get(self, request, *args, **kwargs):
        data = execsys(request.user.username)
        centre = data['section']
        return render(request, 'beweb/assets.html', {'centre': centre
                                                     })


class WoSaveAsset(View):
    def post(self, request, *args, **kwargs):
        reference_number = None
        # IF WORKORDER DOES NOT EXIST, create workorder first
        assignee = request.session['assignee']
        team_members =request.session['teammembers']
        fleet = request.session['fleet']
        if request.session['workorder_exist'] == False:
            username = request.session['username']
            description = request.session['description']
            supervisor = request.session['username']
            data = execsys(request.user.username)
            centre = data['section']
            section = request.session['section']
            centre_code = data['section']
            work_order_id = request.session['work_order']
            date = datetime.now().strftime("%Y%m%d%H%M")
            createdby = request.session['username']
            wo = request.session['work_order']
            job_description = request.session['job_description']
            expected_end_dt = request.session['expected_end_dt']
            section = request.session['section']
            job_number = request.session['job_number']
            trigger = request.session['trigger']
            start_date = request.session['start_date']
            asset_type = request.session['asset_type']
            job_type = request.session['job_type_id']
           

     
      
            if 'E50' in job_type:
                asset_id = request.POST['asset_id']
                asset_name = ''
                asset_number = ''
                asset_serial = ''
                e50_id = e50_id = "E50"+datetime.now().strftime("%Y%m%d%H%M") + \
                    str(random.randrange(000000, 100000))
                station_id = request.POST['asset_id']
            else:
                asset_id = None
                asset_name = None
                asset_number = None
                asset_serial = None

            if 'E60' in job_type:
                asset_id = request.POST['asset_id']
                district = data['centre']
                asset_name = ''
                asset_number = ''
                asset_serial = ''
                e60_id = e60_id = "E60"+datetime.now().strftime("%Y%m%d%H%M") + \
                    str(random.randrange(000000, 100000))
                transformer_id = request.POST['asset_id']
                work_type = request.POST['work_type']
            else:
                asset_id = None
                asset_name = None
                asset_number = None
                asset_serial = None

            wo = save_wo(username, description, supervisor,
                         centre, date, centre_code, work_order_id)
            joid = Save_Job(createdby, assignee, job_type, wo, job_description, expected_end_dt, centre,
                            section, job_number, trigger, start_date, asset_type, reference_number, asset_id)
             
            if 'E50' in job_type:
                save_e50(e50_id, job_number, createdby, station_id)
            else:

beweb/templates/beweb/workorder/create.html
<!DOCTYPE html>
{% extends "beweb/layout.html" %} {% load i18n%} {% block content %} {% if user.is_authenticated %}

<!DOCTYPE html>
<html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{%load staticfiles %}
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="{%static 'beweb/content/style.css'%}" />


	<style>
		body,
		html {
			height: 100%;
		}

		h1,
		h3 {
			text-align: center;
			padding: 0px;
			background-color: #BCCCC;
			color: black;
			font-weight: bold;
			text-align: center;
			height: 100px;
			line-height: 150px;
			background: #BCCCC;
			display: block;
		}

		h6 {

			font-weight: bold;
			display: block;
			text-align: center;
		}

		* {
			box-sizing: border-box;
		}

		/* Add styles to the form container */
		.container {
			position: absolute;
			right: 0;
			margin: 20px;
			max-width: 300px;
			padding: 16px;
			background-color: white;
		}

		/* Full-width input fields */
		input[type=text],
		input[type=password],
		input[type=textarea] {
			width: 100%;
			padding: 15px;
			margin: 5px 0 22px 0;
			border: none;
			background: #ffe5b4;

		}

		input[type=text]:focus,
		input[type=password]:focus,
		input[type=textarea]:focus {
			background-color: #fff8b4;
			outline: none;
		}

		/* Set a style for the submit button */
		.btn {
			background-color: #2B59A2;
			color: white;
			padding: 10px;
			border: none;
			cursor: pointer;
			width: 70%;
			opacity: 0.8;
			position: absolute;
			margin-left: 15px;
			margin-right: 15px;

		}

		.btn:hover {
			opacity: 1;
			color: #ffffff;
		}

		form {
			margin: auto;
			border-right: 10px;
			text-align: center;
			padding-right: 350px;
			padding-left: 350px;
			padding-top: 5px;
		}

		.row {
			margin: 0px;
		}

		.row>label {
			font-weight: bold;
			margin: 15px 0px;
		}
	</style>

</head>

<body>
	{% for field in form %} {{field.error}} {% endfor %}
	<form action="{% url 'beweb:getwoid' %}" method="POST">
		{% csrf_token %}

		<h3>WORK ORDER</h3>
		<div class="form-group row">
			<label for="staticWorkOrderNumber" class="col-sm-4 col-form-label" align="center">
				WORK ORDER NUMBER
			</label>
			<div class="col-sm-4">
				<input type="text" class="form-control" id="staticWorkOrderNumber" readonly name="work_order_id"
					placeholder="" value="{{work_order}}">
			</div>
			<div class="col-sm-4">
			</div>
		</div>

		<div class="form-group row">
			<label for="staticCreator" class="col-sm-4 col-form-label" align="center">
				CREATOR
			</label>
			<div class="col-sm-4">
				<input type="text" class="form-control" id="staticCreator" name="supervisor" readonly placeholder=""
					value="{{username}}">
			</div>
			<div class="col-sm-4">
			</div>
		</div>
		<div class="form-group row" id="centre">
			<label for="staticCentre" class="col-sm-4 col-form-label" align="center">
				CENTRE
			</label>
			<div class="col-sm-4">
				<input type="text" class="form-control" readonly id="staticCentre" name ="centre" value="{{centre}}">
			</div>
			<div class="col-sm-4">
			</div>
		</div>
		<div class="form-group row" id="centres">
			<label for="staticCentre" id="allCentrelabel" class="col-sm-4 col-form-label" align="center">
				CENTRE
			</label>
			<div class="col-sm-4">
				<select id="all_centre" class="form-control">
					<option value="">Select Centre</option>
					{% for centre in allcentres %}
					<option value="{{centre.centre_code}}" name ="centre">{{centre.centrename}}</option>
					{% endfor %}
				</select>
			</div>
			<div class="col-sm-4">
			</div>
		</div>

		<div class="form-group row" style="display:none">
			<label for="staticCentre" class="col-sm-4 col-form-label" align="center">
				CENTRE CODE
			</label>
			<div class="col-sm-4">
				<input type="text" class="form-control-plaintext" readonly name="centre_code" id="centre_code"
					value="{{centre_code}}">
			</div>
			<div class="col-sm-4">
			</div>
		</div>

		<div class="form-group row">
			<label for="staticDescription" class="col-sm-4 col-form-label" align="center">
				DESCRIPTION
			</label>
			<div class="col-sm-6">
				<textarea class="form-control" rows="4" id="Description" name="description" placeholder="Description"
					required></textarea>
			</div>
			<div class="col-sm-4">
			</div>
		</div>
		<div class="form-group row  col-sm-12 d-flex justify-content-center align-content-center">
			<div class="col-md-3">
				<a class="navbar-brand  col-sm-8 pt-sm-0" href="{% url 'beweb:home' %}">
					<input type="button" class="btn  btn-sm btn-block " value="Cancel"
						onclick="return confirm('Are you sure you want to cancel?');" />
				</a>
			</div>

			<div class="col-md-3">
				<a class="navbar-brand  col-sm-8 pt-sm-0" href="#">
					<input type="submit" class="btn  btn-sm  btn-block " value="Create Job"
						onclick="return confirm('Are you sure you want to add job?');" />
				</a>
			</div>
			<div class=" col-md-3">
				<a class="navbar-brand  col-sm-8 pt-sm-0" href="}">
					<input type="Submit" class="btn btn-sm  btn-block " value="Submit"
						formaction="/beweb/save/workorder/"
						onclick="return confirm('Are you sure you want to create workorder?');" />
				</a>

			</div>
		</div>
	</form>

</body>

</html>
<script>
	$(document).ready(function () {
		let centre_code = $('#centre_code').val();
		if (centre_code === "URB" || centre_code === "ENV" || centre_code === "RSP" || centre_code === "NYA" || centre_code === "CHP"
			|| centre_code === "CHM" || centre_code === "MSB" 
			|| centre_code === "GUT" || centre_code === "RUT" || centre_code === "MAS" || centre_code === "MSV" || centre_code === "CHR"
			|| centre_code === "MSG" || centre_code === "MTG") {

			$('#centre').show(); //show only static centre field
			$('#centres').hide(); //hide option to select centres
			$('#centres').css('visibility', 'hidden');
			$('#staticCentre').attr('name', 'centre');
		}
		else {

			$('#centres').show();
			$('#centre').hide();
			$('#centre').css('visibility', 'hidden');
			$('#all_centre').attr('name', 'centre');
		}


	});
</script>

{% endif %} {% endblock %}

beweb/templates/beweb/workorder/workorder_view.html
<!DOCTYPE html>
{% extends "beweb/layout.html" %} {% load i18n%} {% block content %}
<html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{%load staticfiles %}
	<title>Workorder View</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="{%static 'beweb/content/style.css'%}" />
	<style>
		/* Set a style for the submit button */
		.btn {
			background-color: #2B59A2;
			color: white;
			padding: 10px;
			border: none;
			cursor: pointer;
			width: 70%;
			opacity: 0.8;
			position: absolute;
			margin-left: 15px;
			margin-right: 15px;

		}

		.btn:hover {
			opacity: 1;
			color: #ffffff;
		}
	</style>
</head>

<body>
	<!-- {% comment %} {% extends "beweb/dashboard.html" %} {% load i18n%} {% block content %} {% if user.is_authenticated %} {% endcomment %} -->




	<!-- {% for field in form %} {{field.error}} {% endfor %} -->
	<div class="container">
		<form action="{% url 'beweb:getwoid' %}" method="GET">
			{% csrf_token %}

			<h3 class="text-center">WORK ORDER</h3>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label font-weight-bold" align="center">WORK ORDER NUMBER</label>
				<div class="col">
					<input type="text" class="form-control" id="" readonly name="centre" placeholder=""
						value="{{workorder.work_order_id}}">
				</div>
			</div>
			<div class="form-group row">
				<label for="" class="col-sm-4 col-form-label font-weight-bold" align="center">CREATOR</label>
				<div class="col">
					<input type="text" class="form-control" id="staticCreator" name="supervisor" readonly
						placeholder="Full name" value="{{fullname}}">
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label font-weight-bold" align="center">CENTRE</label>
				<div class="col">
					<input type="text" name="" value="{{workorder.centre}}" class="form-control" readonly>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label font-weight-bold" align="center">DESCRIPTION</label>
				<div class="col">
					<textarea class="form-control" id="" name="description" placeholder="Description"
						readonly>{{workorder.description}}</textarea>
				</div>
			</div>

			<div class="form-group row">
				<label class="col-sm-4 col-form-label font-weight-bold" align="center">DATE CREATED</label>
				<div class="col">
					<input name="expected_end_dt" type="text" class="form-control" value="{{workorder.created_on}}"
						readonly>
				</div>
			</div>

			<div class="form-group row">
				<label class="col-sm-4 col-form-label font-weight-bold" align="center">JOBS</label>
				<div class="col">
					<a href="{% url 'beweb:workorder-jobs' workorder.work_order_id %}">{{number_of_jobs}}</a>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label font-weight-bold" align="center">PROGRESS</label>
				<div class="col">
					<input type="text" name="" value="" class="form-control" readonly>
				</div>
			</div>
			<div class="form-group row  col-sm-12 d-flex justify-content-center align-content-center ">
				<div class="col-md-3"></div>

				<div class=" col-md-3">
					<a class="navbar-brand  col-sm-8 pt-sm-0" href="{% url 'beweb:home' %}">
						<input type="button" class="btn btn-sm  btn-block " value="EXIT" />
					</a>
				</div>
				<div class=" col-md-3">
					<a class="navbar-brand  col-sm-8 pt-sm-0" href="">
						<input type="submit" class="btn  btn-sm  btn-block " value="EDIT"
							formaction='/beweb/editwork/?q={{workorder.work_order_id}}' />
					</a>
				</div>
				<div class=" col-md-3">
					<a class="navbar-brand  col-sm-8 pt-sm-0" href="/beweb/addjob/?q={{workorder.work_order_id}}">
						<input type="button" class="btn btn-sm  btn-block " value="ADD JOB" />
					</a>
				</div>
			</div>
		</form>
	</div>
</body>

</html>
{%endblock%}