BEOperations/urls.py
from django.contrib import admin

from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from beweb import forms, views
from datetime import datetime
from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', views.home, name='home'),
    path('api-token-auth/', obtain_auth_token,
         name='api_token_auth'),  # <-- And here
    path('beapi/', include('beapi.urls', namespace='beapi')),
    path('beweb/', include('beweb.urls', namespace='beweb')),
    # path('e117/', include('e117.urls', namespace='e117')),
    path('login/',
         LoginView.as_view
         (
             template_name='beweb/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context={
                 'note': 'Log in',
                 'title': 'Log in',
                 'year': datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),
    path('admin/', admin.site.urls, name="admin"),
    path('api-auth', include('rest_framework.urls')),
    url('^', include('django.contrib.auth.urls')),
    # url(r'^report_builder/', include('report_builder.urls'))
    # url(r'^api-token-auth/', obtain_auth_token)
]

beweb/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . forms import *
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from graphene_django.views import GraphQLView
from .views import *
app_name = 'beweb'

urlpatterns = [
    path('graphql', GraphQLView.as_view( graphiql=True)),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('landing', views.landing, name='landing'),
    path('jobs',views.viewJobs,name='jobs'),
    path('listjobs/',ListJobs.as_view(),name='listjobs'),
    path('sjob',views.seejob,name='sjob'),
    path('editjob/',views.editjob,name='editjob'),
    # path('reassignjob/',views.reassignjob,name='reassignjob'),
    path('changejob/',views.ChangeJob.as_view(),name='changejob'),
    path('job/reassign/',views.JobReassign.as_view(),name='job/reassign'),
    path('job/',views.job,name='job'),
    path('mywork/', workorder, name='mywork'),
    path('api/login', views.login),
    path('addjob/', AddJob.as_view(), name='addjob'),
    path('getteam/', MyTeam.as_view(), name='getteam'),
    path('getmyteam/', MTeam.as_view(), name='getmyteam'),
    path('getasset/', MyAsset.as_view(), name='getasset'),
    path('updatejobasset/', MyjobAsset.as_view(), name='updatejobasset'),
    path('getwoid/', Mywo.as_view(), name='getwoid'),
    path('save/asset/', SaveJobandAddAsset.as_view(), name='SaveJobandAddAsset'),
    path('save/job/', SaveJob.as_view(), name='SaveJob'),
    path('create/e117/', SaveE117Job.as_view(), name='e117-create'),  
    path('saveasset/', WoSaveAsset.as_view(), name='saveasset'),
    path('get_user/', views.get_user, name='get_user'),
    path('addteam/', views.addteam, name='addteam'),
    path('create/', views.create, name='create'),
    path('create_e117/',Create_E117_Job.as_view(),name='create_e117'),
    path('newteam/', views.create_team, name='newteam'),
    path('view_teams/',views.view_Teams,name='view_teams'),
    path('team/<ec_number>',views.view_Team,name='team'),
    path('editteam/',views.editTeam,name='editteam'),  
    path('orders/<ec_num>/', JobsViewSet.as_view(),name="orders"),
    path('openjobs/<username>/<section>/<status>/', JobsViewProcedure.as_view(),name="openjobs"),
    path('progressjobs/<username>/<section>/<status>/', ProgressJobs.as_view(), name="progressjobs"),
    path('jobsreport/<jobtype>/<centre>/<status>/<start_date>/<end_date>/',JobsReports.as_view(),name="jobsreport"),
    path('workorders_report/<workorder_centre>/<workorder_status>/<workorder_start_date>/<workorder_end_date>/',WorkordersReports.as_view(),name="workorders_report"),
    path('rejectedjobs/', ReinspectionJobs.as_view(), name="rejectedjobs"),
    path('supervisorjobs/<username>/<section>/<status>/', SuspendedJobs.as_view(),name="supervisorjobs"),
    path('workorders/<centre>/',WorkorderViewSet.as_view(),name='workorders'),
    path('save/workorder/', OnlySaveWorkorder.as_view(), name='saveworkorder'),
    path('editwork/', editwork, name='editwork'),
    path('edit/', SaveEditedWorkorder.as_view(), name='saveeditedworkorder'),
    path('form/<job_id>/', FormsView.as_view(), name='form'),
    path('Jobworkflow/', views.Job_workflow, name='Jobworkflow'),
    path('forms/', views.listForms, name='forms'),
    path('display/e84/',views.displayE84Form,name='e84-display'),
    path('E117/',views.e117Form,name='e117-display'),
    path('E84/',e84Form,name='e84-view'),
    path('E50/',e50Form,name='e50-view'),
    path('E60/',e60Form,name='e60-view'),
    path('jobprogress/',views.jobprogress,name='jobprogress'),
    path('myjobs/',views.myjobs,name='myjobs'),
    path('<workorder_id>/jobs/',views.workorder_jobs,name='workorder-jobs'),
    path('reports/',views.reports,name='reports'),
    path('e1/<e117_id>',views.generate_pdf,name='e1'),
    path('reinspection/',views.ReInspection,name='reinspection'),
    path('save_reinspection/',SaveReinspection.as_view(),name='save_reinspection'),
    path('close/<job_id>/',ApproveE117.as_view(),name='close-job'),
    path('reject/<job_id>/',views.reject_job,name='reject-job'),
    path('stations/<depot>/', Stations.as_view(),name="stations"),
    path('transformers/<depot>/',Transformers.as_view(),name="transformers"),
    path('approve', ApproveE50.as_view(),name="approve-e50"),
    path('approvee60', ApproveE60.as_view(),name="approve-e60"),
    path('viewreport',ViewReport.as_view(),name="viewreport"),
    path('all_centres/<centreparent>',ParentCentres.as_view(),name='all_centres/'),
    path('deleteworkorder/',views.delworkOrder,name='deleteworkorder/'),
    path("workorder_delete/",Worksdelete.as_view(),name="workorder_delete"),
    path("team/<team_leader>/<specialisation>/",TeamsByCentre.as_view(),name="workorder_delete"),
]

e117/urls.py
from django.urls import path, include
from .views import *
app_name = 'e117'

urlpatterns = [
    path('create/', SaveJob.as_view(), name='job-create')  
]

beweb/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Area(models.Model):
    area = models.CharField(max_length=50, null=True, unique=True)

    def __str__(self):
        return self.area


class Person(models.Model):
    name = models.CharField(max_length=100, verbose_name='full name')


class Employee(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    dob = models.DateField()

e117/models.py
from django.db import models

# Create your models here.

beweb/views.py
import requests
from django.contrib.auth.models import User
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.shortcuts import render, render_to_response,redirect
from django.http import HttpRequest, HttpResponseRedirect
from django.http import HttpResponse
from formtools.wizard.views import SessionWizardView
from django.core.mail import send_mail
import operator
from beapi.models import *
from .forms import *
import json 
import uuid
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import authenticate
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND, HTTP_200_OK)
from rest_framework.response import Response
from django.contrib.auth.models import User
import posixpath
import os
import random
from . forms import NameForm, WorkOrderForm, JobForm, GeneralForm
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django_tables2 import RequestConfig
from .tables import *
from rest_framework import viewsets
from beapi.serializers import *
from django.db.models import Q
from django.db import connection
from . beglobals import *
#graphQl Queries link
from .graphqlqueries import schema


# LIBRARIES FOR generating PDF
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
#
from django.core.mail import EmailMessage


def user_authenticate(username):
    users = User.objects.all()
    for user in users:
        if user.username == username:
            token, created = Token.objects.get_or_create(user=user)
            return user.username, token.key
    return None


@csrf_exempt
@api_view(["POST"])
@permission_classes((AllowAny,))
def login(request):
    username = request.data.get("username")
    password = request.data.get("password")
    if username is None or password is None:
        return Response({'error': 'Please provide both username and password'},
                        status=HTTP_400_BAD_REQUEST)
    user = authenticate(username=username, password=password)
    if not user:
        return Response({'error': 'Invalid Credentials'},
                        status=HTTP_404_NOT_FOUND)
    token, _ = Token.objects.get_or_create(user=user)
    return Response({'token': token.key},
                    status=HTTP_200_OK)


def execsys(ecnum):
    URL = "http://" + beserver + ":8082/users/username/" + ecnum
    r = requests.get(url=URL)
    data = r.json()

    return data


def get_center(centre_code):
    if centre_code == "ER":
        centre = "Regional Office (ER)"
        return centre, centre_code
    if centre_code == "ERM":
        centre = "Eastern Maintenance"
        return centre, centre_code
    if centre_code == "END":
        centre = "Network Development"
        return centre, centre_code
    if centre_code == "MTD":
        centre = "Mutare District"
        return centre, centre_code
    if centre_code == "URB":
        centre = "Mutare Urban"
        return centre, centre_code
    if centre_code == "ENV":
        centre = "Mutare Environs"
        return centre, centre_code
    if centre_code == "MTG":
        centre = "Mutare Garage"
        return centre, centre_code
    if centre_code == "MND":
        centre = "Manicaland District"
        return centre, centre_code
    if centre_code == "NYA":
        centre = "Nyanga"
        return centre, centre_code
    if centre_code == "RSP":
        centre = "Rusape"
        return centre, centre_code
    if centre_code == "CHP":
        centre = "Chipinge"
        return centre, centre_code
    if centre_code == "CHM":
        centre = "Chimanimani"
        return centre, centre_code
    if centre_code == "MSB":
        centre = "Middle Sabi"
        return centre, centre_code
    if centre_code == "MSD":
        centre = "Masvingo District"
        return centre, centre_code
    if centre_code == "MSV":
        centre = "Masvingo Urban"
        return centre, centre_code
    if centre_code == "GUT":
        centre = "Gutu"
        return centre, centre_code
    if centre_code == "MAS":
        centre = "Mashava"
        return centre, centre_code
    if centre_code == "RUT":
        centre = "Rutenga"
        return centre, centre_code
    if centre_code == "CHR":
        centre = "Chiredzi"
        return centre, centre_code
    if centre_code == "MSG":
        centre = "Masvingo Garage"
        return centre, centre_code
    centre = "No Centre"
    centre_code = "No Centre Code"
    return centre, centre_code


class MyTeam(View):
    def get(self, request, *args, **kwargs):
        team_leaders = request.GET['leader']
        myteam, teams = artisan_team(team_leaders)
        data = ""
        team_leaders = []
        Teams = Team.objects.all()
        my_teams = dict()

        for teamleader in Teams:
            if teamleader.team_leader not in [member.team_leader for member in team_leaders]:
                team_leaders.append(teamleader)
                my_teams[teamleader.team_leader] = []

        for teamleader in team_leaders:
            teammembers = Team.objects.filter(team_leader=teamleader)
            if teammembers:
                for teammember in teammembers:
                    my_teams[teamleader.team_leader].append(
                        teammember.team_member)
        return render(request, 'beweb/wo.html', {
            'data': data, 'myteam': myteam, 'my_teams': my_teams, 'teams': teams, 'team_leaders': team_leaders
        })

    def post(self, request, *args, **kwargs):
        members = []
        members = request.POST.getlist('members')
        return HttpResponse('Are you sure you want to save data')


class MTeam(View):
    def get(self, request, *args, **kwargs):
        data = execsys(request.user.username)
        centre_code = data['section']
        username = data['username']
        centre, centre_code = get_center(centre_code)
        centre = request.GET['centre']
        date = datetime.now().strftime("%Y%m%d%H%M")
        centre_code = request.GET['centre_code']
        team_leaders = request.GET['leader']
        myteam = artisan_team(team_leaders)
        data = ""
        return render(request, 'beweb/job/create.html', {
            'data': data, 'myteam': myteam,  'team_leaders': team_leaders
        })


class MyAssets(View):
    def get(self, request, *args, **kwargs):
        data = execsys(request.user.username)
        centre = data['section']
        return render(request, 'beweb/assets.html', {'centre': centre
                                                     })


class WoSaveAsset(View):
    def post(self, request, *args, **kwargs):
        reference_number = None
        # IF WORKORDER DOES NOT EXIST, create workorder first
        assignee = request.session['assignee']
        team_members =request.session['teammembers']
        fleet = request.session['fleet']
        if request.session['workorder_exist'] == False:
            username = request.session['username']
            description = request.session['description']
            supervisor = request.session['username']
            data = execsys(request.user.username)
            centre = data['section']
            section = request.session['section']
            centre_code = data['section']
            work_order_id = request.session['work_order']
            date = datetime.now().strftime("%Y%m%d%H%M")
            createdby = request.session['username']
            wo = request.session['work_order']
            job_description = request.session['job_description']
            expected_end_dt = request.session['expected_end_dt']
            section = request.session['section']
            job_number = request.session['job_number']
            trigger = request.session['trigger']
            start_date = request.session['start_date']
            asset_type = request.session['asset_type']
            job_type = request.session['job_type_id']
           

     
      
            if 'E50' in job_type:
                asset_id = request.POST['asset_id']
                asset_name = ''
                asset_number = ''
                asset_serial = ''
                e50_id = e50_id = "E50"+datetime.now().strftime("%Y%m%d%H%M") + \
                    str(random.randrange(000000, 100000))
                station_id = request.POST['asset_id']
            else:
                asset_id = None
                asset_name = None
                asset_number = None
                asset_serial = None

            if 'E60' in job_type:
                asset_id = request.POST['asset_id']
                district = data['centre']
                asset_name = ''
                asset_number = ''
                asset_serial = ''
                e60_id = e60_id = "E60"+datetime.now().strftime("%Y%m%d%H%M") + \
                    str(random.randrange(000000, 100000))
                transformer_id = request.POST['asset_id']
                work_type = request.POST['work_type']
            else:
                asset_id = None
                asset_name = None
                asset_number = None
                asset_serial = None

            wo = save_wo(username, description, supervisor,
                         centre, date, centre_code, work_order_id)
            joid = Save_Job(createdby, assignee, job_type, wo, job_description, expected_end_dt, centre,
                            section, job_number, trigger, start_date, asset_type, reference_number, asset_id)
             
            if 'E50' in job_type:
                save_e50(e50_id, job_number, createdby, station_id)
            else:

beweb/templates/beweb/job/close.html
{% extends "beweb/layout.html" %} {% load i18n%} {% block content %} {% if user.is_authenticated %}
<html>
<style>
    #dialogoverlay {
        display: none;
        opacity: .4;
        position: fixed;
        top: 0px;
        left: 0px;
        background: #89cff0;
        width: 100%;
        z-index: 10;
    }

    #dialogbox {
        display: none;
        position: fixed;
        background: #2B59A2;
        border-radius: 7px;
        width: 550px;
        z-index: 10;
    }

    #dialogbox>div {
        background: #FFF;
        margin: 8px;
    }

    #dialogbox>div>#dialogboxhead {
        background: #d4d7db;
        font-size: 19px;
        padding: 10px;
        color: #2B59A2;
    }

    #dialogbox>div>#dialogboxbody {
        background: #2B59A2;
        padding: 20px;
        color: #FFF;
    }

    #dialogbox>div>#dialogboxfoot {
        background: #d4d7db;
        padding: 10px;
        text-align: right;
    }

    .btnn {
        background-color: #2B59A2;
        border: solid;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        cursor: pointer;
        border-radius: 12px;
    }
</style>

<body>


    <div id="dialogoverlay"></div>
    <div id="dialogbox">
        <div>
            <div id="dialogboxhead"></div>
            <div id="dialogboxbody"></div>
            <div id="dialogboxfoot"></div>

        </div>
    </div>


</body>

<script>
    $(document).ready(function () {
        function CustomAlert() {
            this.render = function (dialog) {
                let winW = window.innerWidth;
                let winH = window.innerHeight;
                $('#dialogoverlay').css('display', "block");
                $('#dialogoverlay').css('height', winH + "px");
                $('#dialogbox').css('left', (winW / 2) - (550 * .5) + "px");
                $('#dialogbox').css('display', "block");
                $('#dialogboxhead').html("NOTIFICATION");
                $('#dialogboxbody').html(dialog);
                $('#dialogboxfoot').html('<input name="submit" id="ok" type="submit" value="OK" class="btnn" style="border-radius:12px;" />');
            }
        }
        let Alert = new CustomAlert()
        Alert.render("Job closed successfully!")
        $("#ok").click(function () {
            window.location.replace("/beweb/listjobs");
        });
    });
</script>

</html>
{% endif %} {% endblock %}

beweb/templates/beweb/job/myjobs.html
{% extends "beweb/layout.html" %} {% load i18n%} {% block content %} {% if user.is_authenticated %}


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="kk">
    <title>Be Operations - Dashboard</title>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static 'beweb/content/style.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'beweb/DataTables/datatables.min.css' %}" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'beweb/DataTables/datatables.min.js' %}"></script>
</head>

<div class="container d-flex justify-content-center align-content-center ">
    <form method="GET">
        {% csrf_token %}

        <div class="form-group container row d-flex justify-content-center align-content-center">
            <h2 class="text-center font-weight-bold ">MY JOBS</h2>
            <table id="myjobs" class="table table-striped table-bordered table-responsive-md"
                style="background-color:#f4f4f4;border-radius: 5px">
                <thead>
                    <tr>
                        <th style="color: black;">Job ID</th>
                        <th style="color: black;">Job Description</th>
                        <th style="color: black;">Artisan</th>
                        <th style="color: black;">Approve</th>
                        <th style="color: black;">Reject</th>
                    </tr>
                </thead>
                <tbody>
                    {% for jp in data %}
                    <tr>
                        <td><a href="/beweb/myjobs/?q={{jp.job_id}}" style="color: blue;">{{jp.job_id}}</a></td>
                        <td>{{jp.description}}</td>
                        <td>{{jp.artisan}}</td>
                        <td class="d-flex justify-content-start align-content-start ">
                            <a
                                href="/beweb/Jobworkflow/?job_id={{jp.job_id}}&decision={{jp.approve}}&status={{jp.approve}}&opt=Approve"><input
                                    type="button" style="opacity:0.90; color:blue"
                                    class="rounded-lg  btn-sm  btn-block " value="{{jp.nextaction}}" /></a>
                        </td>
                        <td>
                            <a
                                href="/beweb/Jobworkflow/?job_id={{jp.job_id}}&decision={{jp.reject}}&status={{jp.approve}}&opt=reject"><input
                                    type="button" style="opacity:0.90; color:blue"
                                    class="rounded-lg  btn-sm  btn-block " value="Reject job" /></a>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="form-group row  col-sm-12 d-flex justify-content-center align-content-center ">
            <div class=" col-md-2">
                <a class="navbar-brand  col-sm-8 pt-sm-0" href="{% url 'beweb:listjobs' %}">
                    <input type="button" class="btn btn-sm  btn-block " value="BACK" />
                </a>

                {% comment %} </div>
            <div class="col-md-2">
                <a class="navbar-brand  col-sm-8 pt-sm-0" href="/beweb/editjob/?q={{job.job_id}}">
                    <input type="button" class="btn  btn-sm btn-block " value="EDIT" />
                </a>
            </div>
            <div class="col-md-2">
                <a class="navbar-brand  col-sm-8 pt-sm-0" href="/beweb/dashboard">
                    <input type="button" class="btn  btn-sm  btn-block " value="Work orders" />
                </a>
            </div> {% endcomment %}
        </div>
    </form>
</div>
</div>

<script>
    $(document).ready(function () {
        var table = $('#myjobs').DataTable({});
    });
</script>

{% endif %} {% endblock %}

beweb/templates/beweb/job/workorder_jobs.html
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Job Edit</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Jobs</title>
    <meta name="author" content="kk">
    {% load staticfiles %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'beweb/content/style.css'%}" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>

<body>
    <!-- Navigation(Nav Bar) -->
    <nav class="navbar navbar-expand-md sticky-top" style="padding:35px">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{%static 'beweb/img/belogo.png'%}" width="80" height="75">
            </a>
            <a class="navbar-brand" href="#">
                <img src="{% static 'beweb/img/logo.png'%}" width="65" height="65" style="border-radius: 30px;">
            </a>
        </div>
    </nav>
    <!-- Navigation(Nav Bar End)  -->
    <div class="bg">
        <!--Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light sticky-top"
            style="padding:25px;background-color:#FDF2E5;opacity:0.8">
            <div class="container-fluid">
                <div class="dropdown">
                    <a href="" id="imageDropdown" data-toggle="dropdown">
                        <img src="{%static 'beweb/img/apps.png'%}" width="40" height="40">
                    </a>
                    <div class="dropdown-menu">
                        <button class="dropdown-item" type="button"><a tabindex='-1' href="#">Strategic
                                Objectives</a></button>
                        <button class="dropdown-item" type="button"><a tabindex='-1' href="#">Processes and
                                Procedures</a></button>

                        <button class="dropdown-item" type="button"><a tabindex='-1'
                                href="{% url 'beweb:dashboard' %}">Business
                                Applications</a></button>

                        <button class="dropdown-item" type="button"><a tabindex='-1' href="#">Competence
                                Building</a></button>
                        <button class="dropdown-item" type="button"><a tabindex='-1' href="#">Engagement
                                Forums</a></button>
                        <button class="dropdown-item" type="button"><a tabindex='-1' href="#">Knowledge
                                Centre</a></button>
                        <button class="dropdown-item" type="button"><a tabindex='-1'
                                href="{% url 'beweb:landing' %}">Dashboard</a></button>
                    </div>
                </div>
                <ul class="navbar-nav mr-auto nav-tabs">
                    <li class="nav-item active">
                        <a class="nav-link navbar-brand font-weight-bold" href="{% url 'beweb:dashboard' %}">WORK
                            ORDERS</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link navbar-brand font-weight-bold" href="{% url 'beweb:listjobs' %}">JOBS</a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link nav-brand font-weight-bold" href="{% url 'beweb:newteam' %}">TEAMS</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link nav-brand font-weight-bold" href="#">REPORTS</a>
                    </li>
                </ul>
                <div class="collapse navbar-collapse w-100 order-3 dual-collapse2 " id="navbarTogglerDemo01">
                    <a class="nav-link disabled">{% include 'beweb/loginpartial.html' %}</a>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <img src="{% static 'beweb/img/user.png'%}" style="margin-right:  10px">
                            <a class=" mr-sm-2 dropdown-toggle" data-toggle="dropdown">{{ user.username }}<b
                                    class="caret"></b></a>
                            <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                <a class="dropdown-item" href="#">View Profile</a>
                                <a class="dropdown-item" href="{% url 'password_reset' %}">Change Password</a>
                                <a class="dropdown-item"
                                    href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
        <!--/.Navbar -->

        <body>
            <div class="container" style="background-color:#f4f4f4;margin-top:50px;border-radius:15px;">
                <br>
                <h3 class="text-center font-weight-bold">JOBS</h3>

                <table id="orders" class="table table-striped table-bordered table-responsive-md"
                    style="background-color:#f4f4f4;border-radius: 5px" data-server-side="false">
                    <thead>
                        <tr>
                            <th style="color:black">Job Number</th>
                            <th style="color:black">Description</th>
                            <th style="color:black"> Date Created</th>
                            <th style="color:black">Status</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for job in jobs %}
                        <tr>
                            <td><a href='/beweb/job/?q={{job.job_id}}'>{{job.job_id }}</a></td>
                            <td>{{job.description }}</td>
                            <td>{{job.created_on }}</td>
                            <td>{{job.status }}</td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <script type="text/javascript" src="{% static 'beweb/DataTables/datatables.min.js' %}"></script>
            <link rel="stylesheet" type="text/css" href="{% static 'beweb/DataTables/datatables.min.css' %}" />
            <script>
                $(document).ready(function () {
                    var table = $(' #orders').DataTable({});
                }); </script>
        </body>

</html>